sonar.projectKey=MedicoJobs_medicojob-frontend
sonar.sources=src,public
sonar.exclusions=**/node_modules/**,**/build/**,**/.tmp/**,**/coverage/**,**/*.log,**/k8s/**,**/.github/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
